<?php
/**
 * Created by PhpStorm.
 * User: Stepan
 * Date: 23.06.2016
 * Time: 21:45
 */

namespace App\Presenters;


use App\Model\Services\Tags;

class TagsPresenter extends BasePresenter
{
	/** @var Tags @inject  */
	public $tags;

	public function startup()
	{
		parent::startup(); // TODO: Change the autogenerated stub

		$this->steelCheck('Pro správu tagů musíš být přihlášen.', []);

		$this->template->title = 'Tagy';
	}

	public function actionDefault(){
		$tags = $this->tags->findAll();

		$this->template->tags = $tags;
	}

	public function handleDelete($title)
	{
		$tag = $this->tags->findOneBy(['title' => $title]);
		if(!$tag){
			return;
		}

		$this->tags->delete($tag);

		$this->actionDefault();
		$this->redrawControl('tags');
	}
}